### PR TITLE
Mind Map

### LINKED ISSUE #13: Mind-map

### PR DESCRIPTION
**Pull request by utihamartiwi**
When do we use t-test, z-test, F-test, and Kolmogorov-Smirnov?
What if we use categorical data (not numeric)? what if our data is not normally distributed?
What is relationship between binomial and bernoulli? Gamma and exponential? Chi-Square and F?

### CODE REVIEW

**Review by artemkurylev — APPROVED** [review]
Nice mind map, clear and understandable for me

**Review by zakariabeni — APPROVED** [review]
NIce 👍

**Comment by nikitml** [comment]
Great, that'd be a perfect example to explore during the course :)

**Review by nikitml — APPROVED** [review]

**Comment by nikitml** [comment]
@artemkurylev @zakariabeni please, "add review" and "approve" if you think it's done

**Review by artemkurylev — APPROVED** [review]

**Review by artemkurylev — APPROVED** [review]

**Review by artemkurylev — APPROVED** [review]

**Review by artemkurylev — COMMENTED** [review]
Approved

**Pull request merged**
