### PR TITLE
Added Kolmogorov-Smirnov test notebook

### LINKED ISSUE #12: Kolmogorov-Smirnov test

### PR DESCRIPTION
**Pull request by Lehsuby**
This notebook contains a brief description of the test, its propertyes, example of implementation, several practical tasks, and questions for verification

### CODE REVIEW

**Review by artemkurylev — CHANGES_REQUESTED** [review]
Pros:
- Nice structure
- The theoretical part is brief but understandable,
- Nice that you added some coding tasks and self-checking questions
- Conclusion is ok
- Interactions

Advice:
I think it would be nice to make a copy in collab(and add a link to it) to give possibility to interact with notebook without downloading it.

**Comment by Lehsuby** [comment]
> Pros:
> 
> * Nice structure
> * The theoretical part is brief but understandable,
> * Nice that you added some coding tasks and self-checking questions
> * Conclusion is ok
> * Interactions
> 
> Advice:
> I think it would be nice to make a copy in collab(and add a link to it) to give possibility to interact with notebook without downloading it.

Fixed

**Review by artemkurylev — APPROVED** [review]

**Review by utihamartiwi — COMMENTED** [review]
Clear explanation and complete about Kolmogorov-Smirnov, very good

**Comment by nikitml** [comment]
@utihamartiwi please approve, if everything's fine
@jacked97 please review

**Review by jacked97 — APPROVED** [review]

**Review by utihamartiwi — APPROVED** [review]

**Pull request merged**
