### PR TITLE
Student's t-distribution

### LINKED ISSUE #1: Student's t-didtribution

### PR DESCRIPTION
**Pull request by sobir-git**
Maybe not so "draft" :thinking:

### CODE REVIEW

**Review by sergey-jr — COMMENTED** [review]
pros: 
- attention to material by video 
- some interaction
- formulas explained briefly

cons: 
- video takes 8 mins (so for what is material in notebook)
- just one example (with some variations)
- whole material seems to short
- no link to colab to check how interactive works
- images not working well

All seem like "OK", but if you can change something - do it.

**Review by utihamartiwi — COMMENTED** [review]
Good explanation about the distribution. For gamma. in properties part, please give space between theta and variance symbol because the first time I saw it I read like : mu = k(theta)(sigma^2)=k(theta^2), so I thought mu= k(theta^2)

**Comment by nikitml** [comment]
hey @sobir-git , please take a look at Sergey's comments.
@jacked97 please review

**Review by jacked97 — APPROVED** [review]

**Comment by sobir-git** [comment]
This is somehow mixed up with my another branch about gamma-distribution. So comments look like they also belong to gamma-distribution branch.

Anyways, there are no problems. Colab link is added.

**Review by sergey-jr — CHANGES_REQUESTED** [review]
pros:

- attention to material by video (that is optional to view)
- some interaction
- formulas and material explained briefly
- link in collab

cons:
- just one example (with some variations)
- whole material seems too short

Advice:
- add more examples and/or add questions and tasks
- add connection to other tests (if exists)

**Review by sergey-jr — APPROVED** [review]
I like it.
Advice:
- add more examples
- add some tasks and self-questions

**Comment by sergey-jr** [comment]
More good. but:
- need more examples (it's just one?)
- need some tasks.

**Review by utihamartiwi — APPROVED** [review]

**Pull request merged**
