### PR TITLE
Snedecor's F-distribution and F-test

### LINKED ISSUE #4: Snedecor's F-distribution

### LINKED ISSUE #7: Snedecor's F-test

### PR DESCRIPTION
**Pull request by nikitml**

### CODE REVIEW

**Comment by nikitml** [comment]
@hamzakpt @sobir-git @ZamiraKholmatova hey, could you please take a look?

**Review by hamzakpt — APPROVED** [review]

**Review by ZamiraKholmatova — COMMENTED** [review]
1. Maybe, you can give a link instead of giving a lot of formulas (also, look, if they are readable).
In general, the notebook is very informative. Good work, but formulas...

**Comment by sobir-git** [comment]
I've read only halfway through it until got stuck. Here's what so far
(+) Conveniently provided the list of properties and relations with other distributions
(+) Nice interactive plot of F-distribution

What was not clear:
	- For F-test, there is a quote from a medium article and then a formal definition from Wikipedia. It seems to me that the quote is saying "F-test determines _if means are equal_" while Wikipedia is saying  "F-test determines _if variances are equal_". 

Further ideas, which, I think, if implemented will be super-cool:
	- Adding another interactive plot with two plots so as to enable students to compare two plots with different parameters in the same axis (for example the student could see the difference between F(3, 5) and F(5, 3))

**Comment by nikitml** [comment]
> 1. Maybe, you can give a link instead of giving a lot of formulas (also, look, if they are readable).
>    In general, the notebook is very informative. Good work, but formulas...

Thanks! can you please pinpoint which formulae are not readable?

In the `F-distribution` part there's a link to Wikipedia, what another link could be there?

@ZamiraKholmatova

**Comment by nikitml** [comment]
> What was not clear:
> - For F-test, there is a quote from a medium article and then a formal definition from Wikipedia. It seems to me that the quote is saying "F-test determines _if means are equal_" while Wikipedia is saying "F-test determines _if variances are equal_".

Have you seen the **important** notice after the definition? 

> Further ideas, which, I think, if implemented will be super-cool:
> - Adding another interactive plot with two plots so as to enable students to compare two plots with different parameters in the same axis (for example the student could see the difference between F(3, 5) and F(5, 3))

Do you think it's mandatory? 

@sobir-git

**Comment by ZamiraKholmatova** [comment]
> > 1. Maybe, you can give a link instead of giving a lot of formulas (also, look, if they are readable).
> >    In general, the notebook is very informative. Good work, but formulas...
> 
> Thanks! can you please pinpoint which formulae are not readable?
> 
> In the `F-distribution` part there's a link to Wikipedia, what another link could be there?
> 
> @ZamiraKholmatova

For example, the 7th property for me looks like "$ \frac{d_2}{d_1(d_1+d_2-1)} \operatorname{T}^2 (d_1, d_1 +d_2-1) $". Please, check it (but in case, if it is problem with my connection, I'm sorry :) )

**Review by sobir-git — APPROVED** [review]

**Review by ZamiraKholmatova — APPROVED** [review]
Everything is correct!

**Pull request merged**
