### PR TITLE
Chi-squared distribution examples and exercises

### LINKED ISSUE #3: Chi-square distribution

### PR DESCRIPTION
**Pull request by apoyezzhayev**
Some references in text of the notebook are unresolved because they must refer to still not-existing notebooks (like notebook with Chi-squared tests).
These ref-s must be replaced with valid ones after new notebooks will appear.

### CODE REVIEW

**Comment by utihamartiwi** [comment]
good

**Review by utihamartiwi — COMMENTED** [review]
good

**Comment by Lehsuby** [comment]
**Great notebook**: cool examples, theoretical part, exercises, self-checking questions. 
But there are small disadvantages:
- add copy on **Colab** and add **link**
- add **Conclusion** part, where you summaraze key points

**Review by Lehsuby — CHANGES_REQUESTED** [review]
**Great notebook**: cool examples, theoretical part, exercises, self-checking questions.   
  
  
But I would recommend adding a few changes:
- add copy on **Colab** and add **link**
- add **Conclusion** part, where you summaraze key points

**Review by Lehsuby — APPROVED** [review]

**Comment by nikitml** [comment]
@utihamartiwi please approve, if everything's fine
@sobir-git please review

**Review by sobir-git — APPROVED** [review]
he questions you provided are very helpful.
Nice examples to play with. 
Excellent coding exercises.
Overall 11/10 :)

Questions 1:
I liked the questions. I answered the first one. But the second question is vague. For example, what do you mean by N in that question? -- Normal distribution or just a number N?

Good plot of PDF and CDF

Questions 2:
I liked the questions. However I wonder if this question is needed to be answered right away: `1. What are the mean and std of the distributions above?`
Second question is nice. The answer is it's the sum of variables not their pdf graph that we see.

in the third question `3. Does the property of additivity works for any variables from $\chi^2$?` I think you wanted to say `...for any number of variables ...`

Moments of the distribution:
E[X] = k, :thumbsup:
D[X]=2k, D[X] is I guess Var(X), but hard to guess, unfamiliar notation in my opinion.

Questions 3:
`1. When could we approximate $\chi^2$ by Normal distribution and why?` -- With my humble knowledge, it's when degrees of freedom > ~20 because of CLT.

`2. What are the params of the approx $N(\mu, \sigma)$?` Sorry, the question is not clear to me.


Nice to see the connections with other distributions. They all look like a huge family very cloes ties to each other! :)

**Review by utihamartiwi — APPROVED** [review]

**Pull request merged**
